export type Faq = { question: string; answer: string };
export type ContentBlock = { title: string; text: string };
export type ContextLink = { href: string; label: string };

export const websiteOfferings: ContentBlock[] = [
  { title: "Professional company and corporate websites", text: "Organise services, company information, procurement details and approved evidence so buyers can assess your organisation. Define who approves content and who maintains it after launch." },
  { title: "Websites for SMEs and growing businesses", text: "Start with the pages customers need: your offer, relevant experience, contact details and a clear enquiry path. A smaller first release can expand as the business develops its content and operating systems." },
  { title: "Website redesign and migration", text: "Review the existing site before replacing it. Identify useful content, established URLs, enquiry paths and maintenance problems. Plan redirects carefully so a redesign does not discard existing search signals." },
  { title: "WordPress development and support", text: "Use WordPress when content editing and available extensions fit the requirements. Aptpro can support development, troubleshoot an installation, review plugins and improve service structure. Updates, backups and access need an agreed maintenance owner." },
  { title: "Custom websites and Next.js development", text: "Custom development is useful when the interface, performance or integration scope needs more control. Use static delivery where appropriate; treat portals and authenticated workflows as separately scoped software systems." },
  { title: "Product catalogues and e-commerce scope", text: "Present products clearly and define how enquiries or orders are handled. Catalogue and WhatsApp-assisted ordering differ from a complete checkout system. Payment, stock and fulfilment requirements must be reviewed before promising an integration." },
];
export const websiteFoundations: ContentBlock[] = [
  { title: "Responsive design and accessibility", text: "Build layouts for phones, tablets and desktops. Check navigation, readable text, keyboard access, forms and contact actions. A mobile visitor should understand the offer and start an enquiry without struggling with the interface." },
  { title: "SEO foundations and technical SEO", text: "Plan a useful page hierarchy, distinct titles and descriptions, meaningful headings, canonical URLs and contextual links. Include sitemap, robots and appropriate structured data checks. These help discovery and interpretation; rankings are not guaranteed." },
  { title: "Website security and ownership", text: "Review HTTPS, administrative access, dependencies and form or integration handling. Agree domain, hosting and content ownership. WordPress backups and updates need a support plan; a static site has different maintenance requirements." },
  { title: "Performance and reliable delivery", text: "Choose hosting and rendering around the site’s needs. Keep public information in HTML, limit unnecessary scripts and size assets for mobile connections. Test important routes, loading behaviour and enquiry actions before release." },
  { title: "Lead generation and WhatsApp integration", text: "Connect service pages to relevant enquiry actions. WhatsApp links can carry a prepared message; email and telephone remain useful alternatives. Agree how the business receives, assigns and follows up enquiries rather than adding a form with no owner." },
  { title: "Analytics and business-system integration", text: "Scope measurement around useful actions such as enquiries. Analytics, consent requirements and reporting ownership must be agreed. CRM, ERP and other connections depend on available interfaces, permissions and testing; they are not included by default." },
  { title: "Maintenance and existing website support", text: "Agree how updates, content changes, backups and hosting issues will be handled after launch. Aptpro can assess an existing website as well as a new build. Document access and handover so the business can manage its platform." },
];
export const websiteProcess: ContentBlock[] = [
  { title: "Discovery", text: "Identify the business goal, audience, existing site and decision makers. Establish the commercial purpose of the website." },
  { title: "Requirements and scope", text: "Agree pages, functionality, content responsibilities, integrations and acceptance criteria before development begins." },
  { title: "Information architecture", text: "Map services, navigation, search intent and enquiry journeys. For redesigns, account for established URLs and useful content." },
  { title: "Design", text: "Review layouts, brand materials and responsive behaviour. Confirm information and actions before building the full site." },
  { title: "Development", text: "Implement approved content using a suitable platform. Separate public pages from authenticated application requirements." },
  { title: "Security and testing", text: "Check access, dependencies, accessibility, metadata, mobile navigation, routes and contact actions against the agreed scope." },
  { title: "Launch and handover", text: "Coordinate hosting, domain configuration and release checks. Agree a migration recovery or rollback path and document ownership." },
  { title: "Support", text: "Agree maintenance and content responsibilities. Review real enquiries and search data before deciding what to improve next." },
];
export const websiteFaqs: Faq[] = [
  { question: "How much does website design cost in Kenya?", answer: "Cost depends on scope. Page count, content readiness, design, platform, integrations, migration and support affect the quote. Aptpro reviews the requirements before proposing a price; there is no published fixed package." },
  { question: "How long does it take to build a business website?", answer: "The timeline depends on scope, content availability and approvals. A company site differs from a portal or integrated catalogue. Aptpro agrees stages after discovery rather than promising a deadline before reviewing the work." },
  { question: "Does Aptpro build websites for Kenyan SMEs?", answer: "Yes. Aptpro works with SMEs, including those with outdated websites, manual enquiry handling or limited internal IT support. The first release can address the immediate need and leave room for later automation or systems." },
  { question: "Can Aptpro redesign an existing website?", answer: "Yes. Aptpro can review and redesign a business website. The review covers content, URLs, mobile usability, enquiry paths, hosting and maintenance so useful parts of the existing site can be retained." },
  { question: "Does Aptpro work with WordPress or build custom websites?", answer: "Yes. Aptpro supports WordPress development and troubleshooting, and builds custom websites including Next.js implementations. The choice depends on editing needs, functionality, security, performance and support ownership." },
  { question: "Will my website be mobile-friendly?", answer: "Yes. Responsive layouts and mobile navigation are part of the website scope. Important content, contact actions and forms are checked across relevant screen sizes before launch." },
  { question: "Does website development include SEO?", answer: "Website projects include agreed SEO foundations such as page structure, metadata, canonicals, sitemap and technical launch checks. Ongoing content, outreach and search-performance management require a separate scope. Aptpro does not guarantee rankings." },
  { question: "Can Aptpro maintain the website after launch?", answer: "Yes. Maintenance and existing website support can be scoped alongside development. Hosting, updates, backups, content changes and issue-handling responsibilities should be agreed before handover." },
  { question: "Can Aptpro integrate WhatsApp or business systems?", answer: "Yes. Aptpro can add WhatsApp enquiry links and scope business-system connections. Complex integrations require a review of APIs, data ownership, permissions and testing before a delivery commitment." },
  { question: "Does Aptpro work with businesses outside Nairobi?", answer: "Yes. Kenya is Aptpro’s primary market, including businesses outside Nairobi. Remote discovery and website delivery can be scoped across East Africa; on-site work depends on location and engagement requirements." },
];
export type Industry = {
  slug: "veterinary" | "property-management" | "professional-services" | "energy-solar" | "smes";
  label: string; title: string; description: string; intro: string; challenge: string;
  blocks: ContentBlock[]; planning: ContentBlock[]; evidence: string; links: ContextLink[]; faqs: Faq[];
};
export const industries: Industry[] = [
  {
    slug: "veterinary", label: "Veterinary & animal healthcare", title: "Veterinary Systems & IT Services in Kenya",
    description: "Veterinary ERP workflows, PACS/DICOM, laboratory integration planning, infrastructure and security. Explore Aptpro’s public technical experience in Kenya.",
    intro: "Aptpro supports veterinary technology beyond the clinic website. Public experience includes an active veterinary ERP engagement, imaging and PACS configuration, laboratory integration planning and local infrastructure work.",
    challenge: "A veterinary hospital handles owners, animals and clinical cases alongside appointments, pharmacy stock, billing and reporting. When records sit in separate spreadsheets or paper files, staff must repeat entry and reconstruct handovers between reception, clinicians and accounts.",
    blocks: [
      { title: "Practice workflows and business systems", text: "Map client and animal records, appointments, triage, consultations and service delivery. Define where billing and inventory depend on clinical activity. A phased ERP scope identifies the records each role needs rather than replacing every tool at once." },
      { title: "Pharmacy, inventory and billing", text: "Review how medication, supplies and services are recorded and charged. Agree stock responsibilities, permissions and reporting. Inventory and billing integration is an operating requirement, not evidence that every module has already been delivered." },
      { title: "Imaging infrastructure: PACS and DICOM", text: "Public imaging experience includes Orthanc PACS configuration, DICOM connectivity and CT, X-ray and ultrasound workflows. Reliable local access and organised studies help clinical teams use imaging infrastructure. Private network details and clinical records are never part of public case material." },
      { title: "Laboratory connections and migration planning", text: "Equipment and clinical systems need agreed interfaces and result ownership. Aptpro’s laboratory work is technical planning and integration work, with deployment planning status. Existing records need preparation and staged migration where appropriate." },
      { title: "Networks, access and recovery", text: "Review local connectivity and the boundary between public websites and private systems. Role-based access and recovery planning should reflect staff workflows. Infrastructure and cybersecurity are scoped alongside the software requirements." },
    ],
    planning: [{ title: "Start with workflow discovery", text: "Bring examples of record types, handovers and difficult reports. Use anonymised examples; patient and client data should not be sent through a general enquiry." },{ title: "Agree a phased implementation", text: "Identify modules, role permissions and equipment dependencies. Define user testing, migration responsibilities, deployment readiness and training before committing to release." }],
    evidence: "NASCAH Veterinary ERP remains an active development and implementation engagement. Imaging/PACS is represented separately as implemented support; laboratory and local deployment work retain planning labels. No completed hospital-wide rollout is claimed.",
    links: [{href:"/erp-systems",label:"Custom ERP and clinical workflow systems"},{href:"/cybersecurity",label:"Defensive cybersecurity and access reviews"},{href:"/it-infrastructure",label:"Local infrastructure and specialist-system support"},{href:"/projects/veterinary-systems",label:"Read the veterinary engineering case study"}],
    faqs: [
      {question:"Does Aptpro work with veterinary clinics and hospitals?",answer:"Yes. Public experience covers veterinary ERP workflows, PACS/DICOM imaging and laboratory integration planning. Each new engagement is scoped around its systems, equipment and staff roles."},
      {question:"Can a system connect appointments, billing and inventory?",answer:"These workflows can be scoped together. Aptpro maps records, responsibilities and interfaces before defining phased delivery and acceptance checks. Not every module is included in a standard package."},
      {question:"Does Aptpro support PACS and DICOM infrastructure?",answer:"Yes. Public experience includes Orthanc PACS and DICOM connectivity for local imaging. Equipment compatibility, access and deployment requirements are reviewed for each environment."},
      {question:"Is the NASCAH ERP a completed implementation?",answer:"No. The ERP is labelled active implementation. Imaging support and laboratory planning are separate scopes with their own statuses; no completed hospital-wide rollout is claimed."},
    ],
  },
  {
    slug:"property-management",label:"Property & apartments",title:"Property & Apartment Technology Services in Kenya",
    description:"Property websites, viewing enquiries, WhatsApp communication, reporting, network and CCTV planning for apartments and property managers in Kenya.",
    intro:"Aptpro can scope property websites, enquiry handling, business workflows and infrastructure for property managers, apartment operators and real-estate businesses in Kenya. Each engagement begins with a review of the organisation’s existing tools and site requirements.",
    challenge:"Property teams often manage listings, viewing requests and maintenance conversations across spreadsheets and WhatsApp. Multi-property operations need consistent records and a distinction between tenant information, public marketing and private infrastructure.",
    blocks:[
      {title:"Property websites and viewing enquiries",text:"Organise approved listings, locations, availability and viewing requests. Keep enquiry actions clear on mobile. Define who updates property information and what happens when a listing changes or is no longer available."},
      {title:"Communication and workflow automation",text:"Connect enquiries to an agreed follow-up process. WhatsApp links start a relevant conversation; they differ from automated messaging. Scope reminders, handovers or reporting after reviewing tools, permissions and customer-data responsibilities."},
      {title:"Reporting across properties",text:"Define the records management needs before building dashboards. Agree how property, customer and maintenance information is organised and who can change it. Access boundaries between properties may be required."},
      {title:"Networks, CCTV and IT support",text:"Planning considers coverage, power, connectivity, access and support ownership. CCTV/network scope is site-specific; no standard coverage or completed apartment installation is promised. Public pages must not expose private camera or network access."},
    ],
    planning:[{title:"Separate marketing from operations",text:"A website and a private management system have different users and data needs. Agree the first problem, then assess records, integrations and infrastructure."},{title:"Plan for multiple sites",text:"Review how staff coordinate enquiries and service issues across properties. Document account ownership, reporting definitions and local-connectivity dependencies before rollout."}],
    evidence:"Public experience covers websites, business systems, IT support and CCTV planning. A property engagement applies these capabilities to a separately agreed operating scope.",
    links:[{href:"/website-design",label:"Property website design and enquiry journeys"},{href:"/it-infrastructure",label:"Network and CCTV infrastructure planning"},{href:"/automation",label:"Enquiry and reporting workflow automation"},{href:"/erp-systems",label:"Business systems for operational records"}],
    faqs:[{question:"Can Aptpro build a website for apartments?",answer:"Yes. A property website can cover listings, service information, viewing enquiries and WhatsApp contact. Content ownership and updates are agreed before launch."},{question:"Can enquiries connect to a business system?",answer:"That can be assessed. Aptpro reviews tools, data fields and interfaces before scoping a connection. A WhatsApp link alone does not automate a sales pipeline."},{question:"Does Aptpro offer network or CCTV planning?",answer:"Yes, subject to site-specific review of connectivity, power, coverage, access and support. Site requirements determine the proposed delivery scope."},{question:"Can an engagement cover multiple properties?",answer:"Multi-property requirements can be scoped. Reporting, user access and support need an explicit operating model; on-site availability depends on location and the engagement."}],
  },
  {
    slug:"professional-services",label:"Professional services",title:"Websites & Business Systems for Professional Services in Kenya",
    description:"Company websites, enquiry workflows, business records and secure IT support for consultancies and professional-service organisations in Kenya.",
    intro:"Aptpro can help professional-service organisations in Kenya explain their expertise online and organise the work behind an enquiry. Website, workflow and IT scopes follow the firm’s actual requirements.",
    challenge:"A service firm needs buyers to understand its offer and staff to track what happens after contact. Outdated pages, informal email handovers and spreadsheet records make both tasks harder when several people handle one client relationship.",
    blocks:[{title:"Clear company websites",text:"Give services useful explanations of the problem, scope and next step. Present only approved experience and credentials. Procurement visitors need factual evidence and clear contact details rather than generic promises."},{title:"Client enquiries and service delivery",text:"Map intake, assignment, approvals and follow-up before choosing automation. Clarify responsibility without forcing a large system into the first project. Keep confidential documents separate from public enquiry channels."},{title:"Records and reporting",text:"Define the information needed for active work, outstanding tasks and reporting. Consider custom software when existing tools cannot support the required relationships or permissions. Data preparation and adoption belong in the scope."},{title:"Business email and secure access",text:"Review email configuration, account ownership, access and backups. Support should leave documentation the organisation can use. Infrastructure and access reviews can be scoped alongside a website or workflow project."}],
    planning:[{title:"Agree content and evidence",text:"Identify services, credentials and examples authorised for publication. Clarify who approves public material and how enquiries are assigned."},{title:"Define acceptance and handover",text:"Set scope, access roles, testing and support ownership. For daily operational systems, agree training, migration and release planning."}],
    evidence:"A professional-services engagement starts with approved company information, current workflows and the records the team needs. Public examples must be authorised before publication.",
    links:[{href:"/website-design",label:"Professional company website development"},{href:"/automation",label:"Client enquiry and approval automation"},{href:"/erp-systems",label:"Custom business records and reporting"},{href:"/cybersecurity",label:"Business access and security reviews"}],
    faqs:[{question:"Can Aptpro build a consultancy website?",answer:"Yes. Scope can cover service pages, approved experience and enquiry paths. The firm approves professional claims and any regulated-service wording."},{question:"Can workflow work start without replacing every tool?",answer:"Yes. Aptpro can map a specific handover or reporting problem first. Integration or a new system follows a review of existing processes and tools."},{question:"Will confidential client information be published?",answer:"No confidential information should be published. Public evidence must be approved and can describe engineering scope without exposing client records."},{question:"Can you help with email and user access?",answer:"Yes. Business-email configuration, IT support and access reviews can be scoped as related or separate work."}],
  },
  {
    slug:"energy-solar",label:"Energy & solar",title:"Website & IT Services for Energy and Solar Businesses in Kenya",
    description:"Service-led websites, WordPress support, enquiry journeys and workflow planning for energy and solar businesses. Explore Aptpro’s public Tesni experience.",
    intro:"Aptpro helps energy and solar businesses present services clearly and can scope the workflow and IT needs behind enquiries. Public website-support experience includes Tesni Energies.",
    challenge:"A solar business may serve residential customers and commercial buyers with different needs. Its website must explain installation, maintenance, storage and consultation while the team needs a way to follow up requests and keep information current.",
    blocks:[{title:"Service architecture and website support",text:"Organise residential and commercial offers around customer questions. Explain what a consultation covers. Assess existing WordPress technical problems and maintainability before deciding on a rebuild."},{title:"Enquiries and project handovers",text:"Define the path from contact to assessment and follow-up. WhatsApp and email remain useful starting points. Automation should address a documented reporting or handover problem rather than add a disconnected tool."},{title:"Business systems and field records",text:"Review customer records, appointments, stock and reporting where relevant. A workflow or ERP scope depends on existing applications and interfaces. Requirements and stages are agreed for each engagement."},{title:"Infrastructure and remote-site planning",text:"Connectivity, power and access affect site technology. Public infrastructure material includes solar-powered 4G CCTV planning for a farm, with deployment planning status. The scope considers power, connectivity and coverage before deployment."}],
    planning:[{title:"Make services understandable",text:"Bring the current site and service information approved for publication. Identify the questions customers need answered before contacting the team."},{title:"Scope operations separately",text:"Review record types, handovers and reporting gaps. Agree integration feasibility, access and stages before linking the website to a business system."}],
    evidence:"Tesni Energies is represented as implemented website support: service structure, WordPress troubleshooting and service presentation. The recorded scope is website support.",
    links:[{href:"/website-design",label:"Energy business websites and WordPress support"},{href:"/projects#tesni-energies",label:"Tesni Energies website-support evidence"},{href:"/automation",label:"Enquiry and field-workflow integration"},{href:"/it-infrastructure",label:"Connectivity and infrastructure planning"}],
    faqs:[{question:"Does Aptpro have solar-business website experience?",answer:"Yes. Public material records Tesni Energies support involving service structure, WordPress troubleshooting and presentation. The recorded scope is implemented support."},{question:"Can Aptpro improve our WordPress site?",answer:"Yes. Aptpro can assess technical issues, structure and maintenance before recommending changes or a redesign."},{question:"Can enquiries connect to field workflows?",answer:"That can be scoped after reviewing handovers, records and tools. Integration feasibility and data ownership are agreed before implementation."},{question:"How is remote-site infrastructure planned?",answer:"Planning reviews power, connectivity, coverage and authorised access. The public farm CCTV example remains deployment planning, with solar power and 4G considered in the scope."}],
  },
  {
    slug:"smes",label:"SMEs & growing businesses",title:"Websites, Automation & IT Solutions for Kenyan SMEs",
    description:"Start with a website or an operating problem. Aptpro scopes automation, custom systems, infrastructure and security for growing Kenyan SMEs.",
    intro:"Aptpro works with Kenyan SMEs that need professional websites and a more structured technology environment. Start with the immediate problem, then build toward connected records, dependable infrastructure and safer access.",
    challenge:"Many growing businesses depend on Excel, paper and WhatsApp. These tools can work at first, but reporting gets difficult when staff copy information, approvals are unclear and backups depend on one person. Limited internal IT capacity makes maintenance harder.",
    blocks:[{title:"Start with a useful website",text:"Explain services, provide approved evidence and make mobile enquiries easy. A focused site can be the first project; it does not require a large software system. Agree content and maintenance ownership."},{title:"Automate a specific handover",text:"Identify a repeated task: copying enquiries, preparing reports or checking approvals. Review tools and interfaces before automating. Keep a manual fallback and a person responsible for exceptions."},{title:"Move beyond disconnected records",text:"Consider a system when spreadsheets no longer support shared records, roles or reporting reliably. Map customer, stock and billing requirements before selecting modules. Prepare data and test phased changes with staff."},{title:"Make infrastructure supportable",text:"Review email, workstations, networks, applications and backups. Document access and ownership so the business does not depend on one undocumented setup. Separate urgent faults from structural improvements."},{title:"Build security into daily operations",text:"Review permissions, offboarding, backups and website administration. Security work should produce actions staff can follow. Defensive assessments cover authorised systems and do not promise to remove all risk."}],
    planning:[{title:"Choose the first problem",text:"Describe today’s process, who is involved and what success would look like. Distinguish website needs from business-system or IT support problems."},{title:"Build in manageable phases",text:"Agree a first scope, cost factors, responsibilities and acceptance checks. Add integrations or reporting as the business develops the need and capacity to maintain them."}],
    evidence:"Public experience includes website support, business IT support and active ERP work. Each project retains its delivery status so buyers can distinguish implemented support from active development and planning.",
    links:[{href:"/website-design",label:"Website design for Kenyan SMEs"},{href:"/automation",label:"Automation beyond manual handovers"},{href:"/erp-systems",label:"ERP systems and shared business records"},{href:"/it-infrastructure",label:"IT support and backup planning"},{href:"/cybersecurity",label:"Defensive security for growing businesses"}],
    faqs:[{question:"Can Aptpro start with a small business website?",answer:"Yes. Scope follows the pages, content and enquiry paths needed now. Later systems work is optional and scoped separately."},{question:"When should a business move beyond Excel?",answer:"Consider a review when repeated entry, permissions or inconsistent reports make shared work difficult. Assess the workflow and data before choosing a new system."},{question:"Do we need internal IT staff?",answer:"No internal IT team is required to start. The engagement still needs a business owner for decisions, access, approvals and ongoing responsibilities."},{question:"Can Aptpro support SMEs outside Nairobi?",answer:"Yes. Kenya is the primary market. Remote delivery can be scoped across East Africa; on-site work depends on location and requirements."}],
  },
];
export const erpBuyerContent: ContentBlock[] = [
  {title:"From spreadsheets to shared business records",text:"Aptpro develops custom ERP and business software for organisations in Kenya. Identify duplicated records, inconsistent reports and unclear approvals. Requirements analysis establishes which workflows need a shared system and which tools should remain."},
  {title:"Scope roles, migration and acceptance",text:"Define who can view, create, approve and change records. Review data quality before migration. Acceptance checks should cover staff workflows, reporting and role-based access control (RBAC), with stakeholders involved before release."},
  {title:"Architecture and deployment planning",text:"Intranet and cloud delivery differ in connectivity, maintenance and access needs. Agree documentation, training, deployment responsibilities and an appropriate rollback or recovery plan. Integrations depend on interfaces and permissions."},
  {title:"Evidence and a practical first phase",text:"NASCAH demonstrates active ERP work around clinical operations, inventory, billing and access control. Its active status is explicit. A new engagement begins with discovery, not an assumption that every feature has been delivered."},
];
export const erpFaqs: Faq[] = [
  {question:"Does Aptpro develop ERP systems in Kenya?",answer:"Yes. Aptpro develops custom ERP and business systems around workflows, roles, records and reporting. Modules and stages are agreed for each engagement."},
  {question:"Is custom ERP suitable for every SME?",answer:"No. Existing tools may suffice or a focused workflow improvement may be a better first step. Aptpro reviews the operating problem before recommending development."},
  {question:"Can existing records be migrated?",answer:"Migration can be scoped after reviewing quality, formats, ownership and retention. Preparation, trial imports and user checks precede a production change."},
  {question:"Can ERP work include integrations and training?",answer:"Yes, when scoped. Feasibility depends on the other systems; training, documentation and support responsibilities are defined during planning."},
];
export const securityBuyerContent: ContentBlock[] = [
  {title:"What a defensive engagement covers",text:"Aptpro provides cybersecurity services in Kenya: assessments, access reviews, hardening and recovery readiness. Begin with written authorisation, systems in scope and business risks. Public websites and private operational systems may need separate scopes."},
  {title:"Findings management can use",text:"Define the output: observed issues, business impact, priority and practical actions. Agree remediation ownership and verification. An assessment is evidence at a point in time; it does not certify that the organisation is free from risk."},
  {title:"Access, infrastructure and ongoing routines",text:"Review how users receive access, privileges change and accounts are removed. Consider network configuration and backups alongside applications. Connect recommendations to support routines rather than treating security as a single scan."},
];
export const securityFaqs: Faq[] = [
  {question:"Does Aptpro provide cybersecurity services in Kenya?",answer:"Yes. Aptpro focuses on authorised defensive assessments, access reviews, hardening and recovery readiness. Scope and permissions precede technical work."},
  {question:"Can a review cover our website?",answer:"Yes. An authorised scope can cover website access, configuration and dependencies. Hosting and third-party systems require appropriate permission."},
  {question:"Does a security review guarantee protection?",answer:"No. It identifies observed risks and recommended action within scope. Ongoing access management, updates, backups and verification remain important."},
  {question:"What should we share in the first enquiry?",answer:"Share a general description of the concern and desired outcome. Do not send passwords, tokens, sensitive records or private network details through general contact."},
];
export const infrastructureBuyerContent: ContentBlock[] = [
  {title:"IT support for Kenyan business operations",text:"Aptpro provides IT infrastructure and support in Kenya. Public experience includes network troubleshooting, business email, Outlook and QuickBooks support, imaging configuration and local deployment planning. Each environment needs its own diagnosis."},
  {title:"Separate urgent faults from recurring causes",text:"Identify what prevents work now, then review repeated problems. Device, user, network and email issues often cross boundaries. Document changes, access owners and support responsibilities so the next issue is easier to investigate."},
  {title:"Plan recovery and site dependencies",text:"Review connectivity, power, applications, remote access and backups. Agree recovery checks and service ownership. On-site availability and response expectations are engagement-specific; no round-the-clock SLA is claimed."},
  {title:"Keep private systems private",text:"Intranets, imaging and CCTV need access models distinct from public websites. Connect infrastructure planning to cybersecurity where required, keeping permissions and internal architecture out of public material."},
];
export const infrastructureFaqs: Faq[] = [
  {question:"Does Aptpro offer IT support in Kenya?",answer:"Yes. Support can cover users, workstations, networks, email and operational systems. The arrangement depends on the environment and agreed responsibilities."},
  {question:"Can you support local servers and intranets?",answer:"Yes. Scope considers connectivity, access, maintenance and recovery. Public work retains planning labels where rollout is unconfirmed."},
  {question:"Do you provide 24/7 support or a fixed SLA?",answer:"No round-the-clock service or fixed SLA is promised here. Availability, response expectations and escalation must be agreed in the engagement."},
  {question:"Can support include backups and cybersecurity?",answer:"Yes, where scoped. Recovery checks, authorisation and ongoing ownership should be agreed rather than assumed."},
];
