import type { Metadata } from "next";
import Link from "next/link";
import { ConsultationCta } from "@/components/PageSections";
import { Breadcrumbs, ContentGrid, RelatedLinks } from "@/components/SeoSections";
import { SecurityCard, SecurityTerminal } from "@/components/ModernUI";
import { createRouteMetadata } from "@/lib/site-config";
import { defensiveTools, engineeringGroups } from "@/lib/security-engineering";
import { SiteShell } from "@/components/SiteChrome";

export const metadata: Metadata = createRouteMetadata("/cybersecurity/engineering");

export default function SecurityEngineeringPage() {
  return <SiteShell><main className="cyber-page engineering-page">
    <Breadcrumbs items={[{ href: "/cybersecurity", label: "Cybersecurity" }, { href: "/cybersecurity/engineering", label: "Security engineering" }]} />
    <section className="cyber-hero"><div className="section-shell cyber-hero-grid"><div className="cyber-hero-copy"><p className="command-label">$ security-engineering --scope=defensive</p><p className="eyebrow">Aptpro engineering portfolio</p><h1>Security engineering beyond the assessment.</h1><p className="cyber-hero-lede">Aptpro develops focused defensive utilities, reusable detection and analysis concepts, and research prototypes around endpoint, fraud, AI, data and security operations challenges relevant to Kenya and East Africa.</p><div className="hero-actions"><Link className="primary-button security-cta" href="/cybersecurity/netafande">Explore NETAFANDE <span aria-hidden="true">-&gt;</span></Link><Link className="secondary-button" href="/contact">Discuss security engineering</Link></div></div><SecurityTerminal title="engineering-lab" status="DEFENSIVE R&D" footer="SCOPE: AUTHORISED / PUBLIC-SAFE" lines={["focused tooling: built", "platform capability: active development", "research architecture: clearly labelled", "deployment claims: evidence-led"]} /></div></section>
    <section className="section-shell netafande-definition"><div><p className="command-label">$ capability-model --four-layers</p><h2>From security service to reusable defensive capability.</h2></div><div><p><strong>Security services</strong> provide authorised reviews, hardening and operational guidance. <strong>Security engineering</strong> builds defensive tools and infrastructure around defined problems. <strong>Security R&amp;D</strong> explores emerging threats and architectures. <strong>Security product development</strong> turns reusable lessons into platforms such as NETAFANDE.</p><p>This portfolio distinguishes built utilities from prototypes, research and architecture. It does not turn engineering work into a claim of commercial deployment, customer adoption or external endorsement.</p></div></section>
    <section className="cyber-services"><div className="section-shell"><div className="technical-divider"><span>$ defensive-tooling --built-utilities</span><small>8 FOCUSED TOOLS / DEFENSIVE BOUNDARIES</small></div><div className="security-grid">{defensiveTools.map((tool,index) => <SecurityCard key={tool.name} code={`UTIL-${String(index+1).padStart(2,"0")}`} title={tool.name} description={tool.summary} status={tool.status.toUpperCase()} category="DEFENSIVE TOOL" />)}</div><p className="engineering-note">These utilities explore focused defensive problems. They may inform Aptpro's broader thinking around visibility, detection and automation, but no direct NETAFANDE integration is claimed unless separately established.</p></div></section>
    <section className="section-shell engineering-groups"><div className="section-heading compact"><p className="command-label">$ research-portfolio --status-labelled</p><h2>Security R&amp;D and architecture work.</h2><p>Each item is presented at its conservative maturity level.</p></div>{engineeringGroups.map((group) => <section className="engineering-group" key={group.title}><div className="technical-divider"><span>{group.title}</span><small>{group.status}</small></div><div className="engineering-grid">{group.items.map((project) => <article className="engineering-item" key={project.name}><p className="engineering-status">{project.status}</p><h3>{project.name}</h3><p>{project.summary}</p><small>{project.boundary}</small></article>)}</div></section>)}</section>
    <ContentGrid title="AI for defense and securing AI are different disciplines" blocks={[{ title: "AI for cyber defense", text: "AI-assisted SOC triage, event correlation, anomaly detection, threat-intelligence context and fraud analysis use AI to help an analyst understand and prioritise security work." }, { title: "Securing AI systems", text: "AI-security engineering protects AI-enabled applications through retrieval authorisation, tool permissions, secret handling, auditability, data provenance and clear agent boundaries." }, { title: "Data security is security engineering", text: "Security data engineering, classification, access-risk analytics, exfiltration signals and evidence workflows connect security telemetry to the applications and business data Aptpro also understands." }, { title: "Authorisation remains foundational", text: "All monitoring, asset discovery, testing and response discussion is framed around customer-owned or otherwise authorised environments, controlled research and accountable review." }]} />
    <RelatedLinks title="Security engineering in context" links={[{ href: "/cybersecurity/netafande", label: "NETAFANDE endpoint security platform" }, { href: "/cybersecurity", label: "Commercial cybersecurity services" }, { href: "/automation", label: "Business automation and integration" }, { href: "/projects", label: "Public project portfolio" }, { href: "/contact", label: "Discuss a security engineering scope" }]} />
    <div className="cyber-cta"><ConsultationCta title="Discuss a defensive security engineering problem." text="Aptpro can help turn a defined security, data, fraud or automation concern into an authorised research, prototype or implementation scope." /></div>
  </main></SiteShell>;
}