import type { Metadata } from "next";
import Link from "next/link";
import { ConsultationCta, PageHero } from "@/components/PageSections";
import { Breadcrumbs, ContentGrid, RelatedLinks } from "@/components/SeoSections";
import { SiteShell } from "@/components/SiteChrome";
import { createRouteMetadata } from "@/lib/site-config";

export const metadata: Metadata = createRouteMetadata("/projects/veterinary-systems");
export default function VeterinaryCaseStudy() {
  return <SiteShell><main>
    <Breadcrumbs items={[{href:"/projects",label:"Projects"},{href:"/projects/veterinary-systems",label:"Veterinary systems"}]} />
    <PageHero eyebrow="Public engineering case study" title="Veterinary ERP, imaging and integration experience." text="This case study brings together separate public Aptpro scopes around veterinary operations. NASCAH ERP is active implementation, imaging/PACS is implemented support, and laboratory and local deployment work retain planning status." />
    <section className="section-shell seo-section case-study-copy"><h2>Challenge and operating environment</h2><p>A veterinary environment connects customers, animals, clinical cases, appointments, triage, consultation, laboratory, imaging, pharmacy, inventory, billing, reporting and communications. Different roles need different records and permissions.</p><p>The engineering problem is the relationship between these workflows. A website alone cannot resolve internal record handovers, and a software module alone cannot establish reliable imaging access or local connectivity.</p><dl className="case-study-facts"><div><dt>ERP scope and status</dt><dd>NASCAH Veterinary ERP: active development and implementation engagement. No completed hospital-wide rollout is claimed.</dd></div><div><dt>Specialist scopes</dt><dd>Orthanc PACS/DICOM configuration and imaging support are represented as implemented support. Laboratory integration and local intranet deployment retain planning labels.</dd></div></dl></section>
    <ContentGrid title="Public requirements and engineering approach" blocks={[{title:"Workflow and ERP architecture",text:"The public ERP scope connects client and animal records with clinical service delivery, inventory, billing, reporting and communication. Role-based access is explicit. The scope demonstrates operating requirements; it does not certify completion of every module."},{title:"Access and staged migration",text:"ERP involvement includes role-based access, local intranet deployment planning and staged migration where appropriate. Private accounts, permissions, network addresses and migration records are intentionally excluded from this public summary."},{title:"Imaging implementation and technology",text:"Public integration work includes Orthanc PACS, DICOM connectivity and CT, X-ray and ultrasound workflows, with local imaging access. This is a separate implemented-support scope rather than evidence that the ERP and imaging systems have all been deployed as one production platform."},{title:"Laboratory integration planning",text:"Public work involves veterinary laboratory equipment and clinical-system workflows. Workflow mapping and system design are represented with deployment planning status. A completed production laboratory interface is not claimed."},{title:"Local infrastructure and deployment planning",text:"The public local-hosting scope includes Windows-based hosting and multi-computer access planning for business applications. Connectivity and private access form part of deployment requirements. No internal topology or operational configuration is disclosed."},{title:"Security and operational boundaries",text:"RBAC is part of the recorded ERP work. No penetration-test result, compliance certification or zero-risk assertion is claimed. Access and private operational records stay separate from the public case material."}]} />
    <section className="section-shell seo-section case-study-copy"><h2>Operational capability and evidence limits</h2><p>The ERP engagement is working toward integrated workflows, controlled access and reporting. Imaging support addresses organised studies and local access. Laboratory integration remains planning work. These scopes show technical specificity without inventing ROI, patient outcomes or a completed end-to-end deployment.</p><p>Future case-study updates should follow approved evidence and the actual delivery status. Client records, private architecture and confidential commercial information must remain outside public content.</p><Link className="inline-link" href="/projects">Review all public projects and their delivery statuses</Link></section>
    <RelatedLinks links={[{href:"/industries/veterinary",label:"Technology requirements for veterinary organisations"},{href:"/erp-systems",label:"Custom ERP requirements and phased delivery"},{href:"/it-infrastructure",label:"Local and specialist infrastructure support"},{href:"/cybersecurity",label:"Authorised defensive cybersecurity"}]} />
    <ConsultationCta title="Need to connect software requirements with the clinical operating environment?" text="Describe the workflow and equipment categories first. Use public-safe requirements in the initial conversation; do not send clinical records or credentials." />
  </main></SiteShell>;
}
