import type { Metadata } from "next";
import { ConsultationCta, PageHero } from "@/components/PageSections";
import { Breadcrumbs, ContentGrid, FaqSection, RelatedLinks, ServiceSchema } from "@/components/SeoSections";
import { SiteShell } from "@/components/SiteChrome";
import { createRouteMetadata } from "@/lib/site-config";

export const metadata: Metadata = createRouteMetadata("/automation");
export default function AutomationPage() {
  return <SiteShell><main>
    <Breadcrumbs items={[{href:"/services",label:"Services"},{href:"/automation",label:"Automation & integration"}]} />
    <ServiceSchema path="/automation" name="Business automation and system integration in Kenya" description="Workflow mapping, integration feasibility and scoped automation for reporting, approvals and business handovers." serviceType={["Business process automation","System integration","Workflow digitisation"]} />
    <PageHero eyebrow="Business automation · Kenya" title="Business automation and integrations built around a defined workflow." text="Aptpro helps organisations in Kenya assess repeated tasks, disconnected records and reporting handovers. Map the process first, then decide whether an integration, a workflow change or custom software is the right response." />
    <ContentGrid title="Where automation can fit" blocks={[{title:"Enquiry and customer handovers",text:"Review how website or email enquiries reach the person responsible for action. Define required fields, assignment and exceptions. WhatsApp contact links are useful, but they do not automatically synchronise customer records."},{title:"Reporting and repeated entry",text:"Identify where staff copy records between tools or assemble the same report repeatedly. Confirm definitions and data quality before automating. An unreliable source becomes a faster unreliable report if the underlying problem is ignored."},{title:"Approvals and operational records",text:"Map who initiates, checks and approves an action. Role permissions, audit requirements and exception handling shape the scope. ERP development and a focused automation are different options; neither is assumed before discovery."},{title:"Specialist and business-system integration",text:"Connections depend on APIs, supported equipment interfaces, access and data ownership. Public experience includes PACS/DICOM work and laboratory integration planning. That does not establish compatibility with every product or vendor."}]} />
    <ContentGrid title="Engineering checks before a workflow is automated" blocks={[{title:"Requirements and feasibility",text:"Define inputs, outputs, owners and acceptance criteria. Review interface documentation, permissions and limits. Confirm what happens when a service is unavailable or the input is incomplete."},{title:"Testing, release and support",text:"Test representative workflows and exceptions. Agree deployment ownership, documentation and a manual fallback or rollback path. The team needs to understand how to detect and handle failures after release."},{title:"AI automation: assess the task first",text:"AI may be worth evaluating when a workflow needs classification or summarisation, but not every task needs it. Any proposed AI work requires a separate feasibility, privacy, human-review and cost assessment before a delivery commitment."}]} />
    <FaqSection faqs={[{question:"Does Aptpro offer business automation in Kenya?",answer:"Yes. Aptpro can scope workflow mapping, integration and automation around a defined business process. The existing tools and available interfaces determine feasibility."},{question:"Can our current systems be connected?",answer:"Possibly. Aptpro needs to review supported interfaces, access, licensing, data ownership and testing requirements before promising a connection."},{question:"Do we need a complete ERP to automate a task?",answer:"No. A process change or focused integration may be sufficient. A requirements review distinguishes those options from a custom business-system project."},{question:"Can AI be included in an automation project?",answer:"Potential AI-assisted workflows require a separate feasibility and risk review. Suitability depends on the task, data sensitivity, quality checks, human oversight and operating costs."}]} />
    <RelatedLinks links={[{href:"/website-design",label:"Websites and lead-generation journeys"},{href:"/erp-systems",label:"Custom business systems and reporting"},{href:"/industries/property-management",label:"Property enquiry and management workflows"},{href:"/industries/smes",label:"Phased technology improvements for SMEs"},{href:"/projects/veterinary-systems",label:"Specialist integration engineering experience"}]} />
    <ConsultationCta title="Which repeated task causes the most friction?" text="Describe the current process, tools, people involved and expected output. Aptpro can help identify a manageable first scope." />
  </main></SiteShell>;
}
