import type { Metadata } from "next";
import Link from "next/link";
import { ConsultationCta } from "@/components/PageSections";
import { Breadcrumbs, ContentGrid, JsonLd, RelatedLinks, providerId } from "@/components/SeoSections";
import { SecurityCard, SecurityTerminal } from "@/components/ModernUI";
import { absoluteUrl, createRouteMetadata } from "@/lib/site-config";
import { SiteShell } from "@/components/SiteChrome";

export const metadata: Metadata = createRouteMetadata("/cybersecurity/netafande");
const modules = [
  ["NF-ENDPOINT", "Endpoint visibility", "Endpoint telemetry, device status and security-posture context.", "ENGINEERING PLATFORM"],
  ["NF-DETECT", "Detection & analysis", "Defensive detection, behavioural signals and event correlation concepts.", "ACTIVE DEVELOPMENT"],
  ["NF-INTEL", "Threat intelligence", "Indicator handling and context enrichment for analyst investigation.", "ENGINEERING PLATFORM"],
  ["NF-TRIAGE", "Investigation workflow", "Prioritisation, evidence organisation and incident timelines.", "ACTIVE DEVELOPMENT"],
  ["NF-RESPOND", "Controlled response", "Authorised playbooks, escalation and case-oriented response workflows.", "HUMAN OVERSIGHT"],
  ["NF-REPORT", "Security reporting", "Posture, technical findings, incident summaries and management context.", "ENGINEERING PLATFORM"],
] as const;

export default function NetafandePage() {
  const softwareSchema = { "@context": "https://schema.org", "@type": "SoftwareApplication", "@id": `${absoluteUrl("/cybersecurity/netafande")}#software`, name: "NETAFANDE", applicationCategory: "SecurityApplication", description: "A Kenya-first endpoint security and security operations engineering platform developed by Aptpro.", url: absoluteUrl("/cybersecurity/netafande"), creator: { "@id": providerId }, offers: undefined };
  return <SiteShell><main className="cyber-page netafande-page"><JsonLd data={softwareSchema} />
    <Breadcrumbs items={[{ href: "/cybersecurity", label: "Cybersecurity" }, { href: "/cybersecurity/netafande", label: "NETAFANDE" }]} />
    <section className="cyber-hero"><div className="section-shell cyber-hero-grid"><div className="cyber-hero-copy"><p className="command-label">$ netafande --mode=defensive-engineering</p><p className="eyebrow">Aptpro security product development</p><h1>NETAFANDE</h1><p className="netafande-subtitle">Kenya-first endpoint security &amp; security operations platform</p><p className="cyber-hero-lede">NETAFANDE is a cybersecurity engineering platform developed by Aptpro to bring endpoint visibility, defensive detection, security analysis and controlled response workflows into a layer designed around the operational needs of Kenyan organisations.</p><div className="hero-actions"><Link className="primary-button security-cta" href="/contact">Discuss NETAFANDE <span aria-hidden="true">-&gt;</span></Link><Link className="secondary-button" href="/cybersecurity">Cybersecurity services</Link></div></div><SecurityTerminal title="netafande" status="ACTIVE DEVELOPMENT" footer="STATUS: ENGINEERING PLATFORM" lines={["endpoint visibility: conceptual modules ready", "detection + correlation: analyst-led", "response workflow: authorised scope", "implementation details: withheld"]} /></div></section>
    <section className="section-shell netafande-definition"><div><p className="command-label">$ product-definition --public</p><h2>What is NETAFANDE?</h2></div><div><p>Developed by Aptpro, NETAFANDE is an active security-engineering platform rather than a claimed mass-market or enterprise-proven deployment. It is intended for organisations that need a more structured view of endpoint security, alerts and response work without assuming a large always-on SOC.</p><p>Kenya-first is a design philosophy: it considers mixed Windows environments, distributed endpoints, cost sensitivity, legacy applications, variable connectivity and teams moving from informal IT administration toward structured security operations. It does not imply government approval, certification or national infrastructure status.</p></div></section>
    <section className="feature-band security-band"><div className="section-shell"><div className="section-heading compact"><p className="command-label">$ conceptual-architecture --show</p><h2>A public capability model, not an internal topology.</h2></div><ol className="netafande-flow"><li>Authorised endpoints</li><li>Security telemetry</li><li><strong>NETAFANDE</strong></li><li>Detection &amp; correlation</li><li>Analysis &amp; triage</li><li>Controlled response</li><li>Reporting</li></ol><p className="netafande-support">Supporting context may include authorised threat intelligence, network signals and identity events. Private protocols, detection rules, schemas, APIs and deployment details are intentionally withheld.</p></div></section>
    <section className="cyber-services"><div className="section-shell"><div className="technical-divider"><span>$ capability-model --modules</span><small>PUBLIC PRESENTATION LABELS / NOT INTERNAL MODULE NAMES</small></div><div className="security-grid">{modules.map(([code,title,description,status]) => <SecurityCard key={code} code={code} title={title} description={description} status={status} category="NETAFANDE" />)}</div></div></section>
    <ContentGrid title="Where NETAFANDE sits in Aptpro's security model" blocks={[{ title: "Endpoint through response", text: "NETAFANDE focuses primarily on endpoint visibility, monitoring, detection, analysis, triage and authorised response workflows. Aptpro's broader services extend across identity, network, application, data, backup and recovery." }, { title: "Analyst-assisted, not autonomous containment", text: "AI-assisted analysis may help summarise alerts, correlate context and support investigation. Sensitive containment decisions retain human oversight and authorised controls." }, { title: "Built for practical operating conditions", text: "The platform's design direction recognises that security operations may need to work across mixed devices, limited staffing, changing infrastructure and uneven security maturity." }, { title: "Status with technical honesty", text: "Public language describes NETAFANDE as an engineering platform in active development. The page makes no customer, deployment, partnership, performance or certification claim." }]} />
    <RelatedLinks title="Continue the security engineering conversation" links={[{ href: "/cybersecurity", label: "Cybersecurity services and security reviews" }, { href: "/cybersecurity/engineering", label: "Security engineering, AI and data research" }, { href: "/projects", label: "Cybersecurity engineering in the project portfolio" }, { href: "/contact", label: "Request a technical discussion" }]} />
    <div className="cyber-cta"><ConsultationCta title="Discuss endpoint security and NETAFANDE." text="Describe the security-operating problem, endpoint environment and desired outcome. Aptpro can discuss a defensible scope without exposing implementation internals." /></div>
  </main></SiteShell>;
}